import React from "react";
import {useState} from "react";

const Rubix=()=>{

    // const {rubixArray,setRubixArray} = useState[[
    //  ["w","w","w"]
    // ,["w","w","w"]
    // ,["w","w","w"]], //end white side 0,2,2
    // [["r","r","r"]  
    // ,["r","r","r"]
    // ,["r","r","r"]], //end red side 1,2,2
    // [["b","b","b"]
    // ,["b","b","b"]
    // ,["b","b","b"]], //end blue side 2,2,2
    // [["o","o","o"]
    // ,["o","o","o"]
    // ,["o","o","o"]], //end orange side 3,2,2
    // [["g","g","g"]
    // ,["g","g","g"]
    // ,["g","g","g"]],//end green side 4,2,2
    //  ["y","y","y"]
    // ,["y","y","y"]
    // ,["y","y","y"]] //end yellow side 5,2,2
    // //end rubix array


    return(
        <div>
            {/* so we need to make a 3x3 grid that displays the first 9 tiles of the rubix cube  `rubixArray[i][j][k]`*/}
            {/* {rubixArray[0].forEach(<section className="side">{rubixArray[0][j][k]}</section>)} */}
            hello
        </div>
    )
}

export default Rubix;